import { Card, Deck, DeckTheme, Language } from './types';

export const ALL_LANGUAGES: Language[] = Object.values(Language);

export const INITIAL_DECKS: Deck[] = [
  {
    theme: DeckTheme.NONE,
    name: 'WHAT!? Powered Deck (Free)',
    description: 'Unleash pure chaos and unexpected hilarity! These free-for-all cards guarantee side-splitting moments every round.',
    cards: [
      { id: 'free-1', text: 'I can\’t believe I lost my job because of ____', type: 'prompt', deckTheme: DeckTheme.NONE },
      { id: 'free-2', text: 'My therapist says I need to stop blaming ____', type: 'prompt', deckTheme: DeckTheme.NONE },
      { id: 'free-3', text: 'Joe Rogan', type: 'answer', deckTheme: DeckTheme.NONE },
      { id: 'free-4', text: 'Joe Rogan’s Elk Meat', type: 'answer', deckTheme: DeckTheme.NONE },
      { id: 'free-5', text: 'The prophecy was written on a napkin about ____', type: 'prompt', deckTheme: DeckTheme.NONE },
      { id: 'free-6', text: 'My emotional support raccoon is obsessed with ____', type: 'answer', deckTheme: DeckTheme.NONE },
      { id: 'free-7', text: 'The real reason dinosaurs went extinct? ____', type: 'prompt', deckTheme: DeckTheme.NONE },
      { id: 'free-8', text: 'My grandma got banned from Facebook for ____', type: 'answer', deckTheme: DeckTheme.NONE },
    ],
    cost: 0,
    unlocked: true,
  },
  {
    theme: DeckTheme.DISNEY_APRILCOTS,
    name: 'Disney Apricots (Pre-2012 Disney Movies, TV, Disneyland)',
    description: 'Journey into the enchanting realm of classic Disney! From beloved characters to iconic park adventures, relive the magic and create new, hilarious memories.',
    cards: [
      { id: 'disney-1', text: 'Mickey Mouse', type: 'answer', deckTheme: DeckTheme.DISNEY_APRILCOTS },
      { id: 'disney-2', text: 'A Dream Is ____', type: 'prompt', deckTheme: DeckTheme.DISNEY_APRILCOTS },
      { id: 'disney-3', text: 'The Evil Queen', type: 'answer', deckTheme: DeckTheme.DISNEY_APRILCOTS },
      { id: 'disney-4', text: 'When You Wish Upon ____', type: 'prompt', deckTheme: DeckTheme.DISNEY_APRILCOTS },
      { id: 'disney-5', text: 'A Whole New ____', type: 'prompt', deckTheme: DeckTheme.DISNEY_APRILCOTS },
      { id: 'disney-6', text: 'Tinker Bell', type: 'answer', deckTheme: DeckTheme.DISNEY_APRILCOTS },
      { id: 'disney-7', text: 'Hakuna ____', type: 'prompt', deckTheme: DeckTheme.DISNEY_APRILCOTS },
      { id: 'disney-8', text: 'A Dole Whip', type: 'answer', deckTheme: DeckTheme.DISNEY_APRILCOTS },
    ],
    cost: 100,
    unlocked: false,
  },
  {
    theme: DeckTheme.MARVEL_APRILCOTS,
    name: 'Marvel Apricots',
    description: 'Assemble your ultimate team! Dive into the epic sagas of the Marvel Universe, featuring legendary heroes, formidable villains, and universe-shaking events.',
    cards: [
      { id: 'marvel-1', text: 'Iron Man', type: 'answer', deckTheme: DeckTheme.MARVEL_APRILCOTS },
      { id: 'marvel-2', text: 'Avengers: ____', type: 'prompt', deckTheme: DeckTheme.MARVEL_APRILCOTS },
      { id: 'marvel-3', text: 'Thanos', type: 'answer', deckTheme: DeckTheme.MARVEL_APRILCOTS },
      { id: 'marvel-4', text: 'With great power comes ____', type: 'prompt', deckTheme: DeckTheme.MARVEL_APRILCOTS },
      { id: 'marvel-5', text: 'Wakanda ____', type: 'prompt', deckTheme: DeckTheme.MARVEL_APRILCOTS },
      { id: 'marvel-6', text: 'Mjolnir', type: 'answer', deckTheme: DeckTheme.MARVEL_APRILCOTS },
      { id: 'marvel-7', text: 'I am inevitable… ____', type: 'prompt', deckTheme: DeckTheme.MARVEL_APRILCOTS },
      { id: 'marvel-8', text: 'A Hulk smash', type: 'answer', deckTheme: DeckTheme.MARVEL_APRILCOTS },
    ],
    cost: 100,
    unlocked: false,
  },
  {
    theme: DeckTheme.STAR_WARS_APRILCOTS,
    name: 'Star Wars Apricots',
    description: 'Embark on an epic journey to a galaxy far, far away! Encounter legendary Jedi, fearsome Sith, and iconic moments that shaped the Star Wars saga.',
    cards: [
      { id: 'starwars-1', text: 'Luke Skywalker', type: 'answer', deckTheme: DeckTheme.STAR_WARS_APRILCOTS },
      { id: 'starwars-2', text: 'May the ____ be with you', type: 'prompt', deckTheme: DeckTheme.STAR_WARS_APRILCOTS },
      { id: 'starwars-3', text: 'Darth Vader', type: 'answer', deckTheme: DeckTheme.STAR_WARS_APRILCOTS },
      { id: 'starwars-4', text: 'I am your ____', type: 'prompt', deckTheme: DeckTheme.STAR_WARS_APRILCOTS },
      { id: 'starwars-5', text: 'This is the way of ____', type: 'prompt', deckTheme: DeckTheme.STAR_WARS_APRILCOTS },
      { id: 'starwars-6', text: 'The Millennium Falcon', type: 'answer', deckTheme: DeckTheme.STAR_WARS_APRILCOTS },
      { id: 'starwars-7', text: 'The Force compels ____', type: 'prompt', deckTheme: DeckTheme.STAR_WARS_APRILCOTS },
      { id: 'starwars-8', text: 'A blue lightsaber', type: 'answer', deckTheme: DeckTheme.STAR_WARS_APRILCOTS },
    ],
    cost: 100,
    unlocked: false,
  },
  {
    theme: DeckTheme.HOLLYWOOD_LAND_APRILCOTS,
    name: 'Hollywood Land Apricots (1920s-1950s)',
    description: 'Step back in time to the Golden Age of Hollywood! Classic movie quotes, legendary stars, and unforgettable moments from the silver screen. Perfect for film buffs!',
    cards: [
      { id: 'hollywood-1', text: 'Humphrey Bogart', type: 'answer', deckTheme: DeckTheme.HOLLYWOOD_LAND_APRILCOTS },
      { id: 'hollywood-2', text: 'Frankly, my dear, I don\’t give a ____', type: 'prompt', deckTheme: DeckTheme.HOLLYWOOD_LAND_APRILCOTS },
      { id: 'hollywood-3', text: 'Marilyn Monroe', type: 'answer', deckTheme: DeckTheme.HOLLYWOOD_LAND_APRILCOTS },
      { id: 'hollywood-4', text: 'Here’s looking at you, ____', type: 'prompt', deckTheme: DeckTheme.HOLLYWOOD_LAND_APRILCOTS },
      { id: 'hollywood-5', text: 'Of all the gin joints in all the towns in all the world, she walks into ____', type: 'prompt', deckTheme: DeckTheme.HOLLYWOOD_LAND_APRILCOTS },
      { id: 'hollywood-6', text: 'Play it again, ____', type: 'prompt', deckTheme: DeckTheme.HOLLYWOOD_LAND_APRILCOTS },
      { id: 'hollywood-7', text: 'You can\’t handle the ____', type: 'prompt', deckTheme: DeckTheme.HOLLYWOOD_LAND_APRILCOTS },
      { id: 'hollywood-8', text: 'Nobody puts ____ in a corner', type: 'prompt', deckTheme: DeckTheme.HOLLYWOOD_LAND_APRILCOTS },
      { id: 'hollywood-9', text: 'A backlot studio', type: 'answer', deckTheme: DeckTheme.HOLLYWOOD_LAND_APRILCOTS },
      { id: 'hollywood-10', text: 'A silver screen', type: 'answer', deckTheme: DeckTheme.HOLLYWOOD_LAND_APRILCOTS },
      { id: 'hollywood-11', text: 'A director\’s megaphone', type: 'answer', deckTheme: DeckTheme.HOLLYWOOD_LAND_APRILCOTS },
      { id: 'hollywood-12', text: 'A clapperboard', type: 'answer', deckTheme: DeckTheme.HOLLYWOOD_LAND_APRILCOTS },
    ],
    cost: 100,
    unlocked: false,
  },
  {
    theme: DeckTheme.STAND_UP_COMEDY,
    name: 'Stand-Up Comedy',
    description: 'Get ready to laugh until your sides hurt! Hilarious prompts and punchlines inspired by the greatest stand-up acts and comedy specials.',
    cards: [
      { id: 'comedy-1', text: 'My biggest fear is ____', type: 'prompt', deckTheme: DeckTheme.STAND_UP_COMEDY },
      { id: 'comedy-2', text: 'A heckler', type: 'answer', deckTheme: DeckTheme.STAND_UP_COMEDY },
      { id: 'comedy-3', text: 'What\’s the deal with ____?', type: 'prompt', deckTheme: DeckTheme.STAND_UP_COMEDY },
      { id: 'comedy-4', text: 'Audience participation', type: 'answer', deckTheme: DeckTheme.STAND_UP_COMEDY },
      { id: 'comedy-5', text: 'My set just bombed because of ____', type: 'prompt', deckTheme: DeckTheme.STAND_UP_COMEDY },
      { id: 'comedy-6', text: 'A tight 5', type: 'answer', deckTheme: DeckTheme.STAND_UP_COMEDY },
      { id: 'comedy-7', text: 'You know you\’re getting old when ____', type: 'prompt', deckTheme: DeckTheme.STAND_UP_COMEDY },
      { id: 'comedy-8', text: 'The red light', type: 'answer', deckTheme: DeckTheme.STAND_UP_COMEDY },
      { id: 'comedy-9', text: 'My parents don\’t understand my ____', type: 'prompt', deckTheme: DeckTheme.STAND_UP_COMEDY },
      { id: 'comedy-10', text: 'My Netflix special', type: 'answer', deckTheme: DeckTheme.STAND_UP_COMEDY },
      { id: 'comedy-11', text: 'I just flew in from ____ and boy are my arms tired!', type: 'prompt', deckTheme: DeckTheme.STAND_UP_COMEDY },
      { id: 'comedy-12', text: 'A prop comic', type: 'answer', deckTheme: DeckTheme.STAND_UP_COMEDY },
    ],
    cost: 100,
    unlocked: false,
  },
  {
    theme: DeckTheme.HOLLYWOOD_ICONS,
    name: 'Hollywood Icons',
    description: 'Relive cinematic history with legendary movie quotes and iconic moments from Hollywood\’s greatest films. Lights, camera, action!',
    cards: [
      { id: 'icons-1', text: 'I\’ll have what she\’s having', type: 'prompt', deckTheme: DeckTheme.HOLLYWOOD_ICONS },
      { id: 'icons-2', text: 'A double cheeseburger', type: 'answer', deckTheme: DeckTheme.HOLLYWOOD_ICONS },
      { id: 'icons-3', text: 'Here\’s Johnny!', type: 'prompt', deckTheme: DeckTheme.HOLLYWOOD_ICONS },
      { id: 'icons-4', text: 'The axe in the door', type: 'answer', deckTheme: DeckTheme.HOLLYWOOD_ICONS },
      { id: 'icons-5', text: 'May the Force be with you', type: 'prompt', deckTheme: DeckTheme.HOLLYWOOD_ICONS },
      { id: 'icons-6', text: 'A galaxy far, far away', type: 'answer', deckTheme: DeckTheme.HOLLYWOOD_ICONS },
      { id: 'icons-7', text: 'You can\’t handle the truth!', type: 'prompt', deckTheme: DeckTheme.HOLLYWOOD_ICONS },
      { id: 'icons-8', text: 'The courtroom drama', type: 'answer', deckTheme: DeckTheme.HOLLYWOOD_ICONS },
    ],
    cost: 150,
    unlocked: false,
  },
];
